[package]
name = "usql"
version = "0.1.0"
description = "Umbra's (mostly) friendly CLI client"
edition = "2024"

[dependencies]
rustyline = { version = "16.0.0", features = ["derive"] }
umbra = {path = ".."}
